stages/bootc.install-to-fs: remount /dev/shm in addition to /dev/shm
In commit c1f5f50d8ce6340dae98fb2d3604dcfc65ce546e we introduced the
remounting of /dev. However, wit this /dev, podman, as started from
image-builder ends up with this error:

```
Error: failed to get new shm lock manager: failed to create 2048 locks in /libpod_lock: no such file or directory
```

This is due to the lack of /dev/shm, so mount it as well

Signed-off-by: Alexander Larsson <alexl@redhat.com>