Many: update mypy to 1.19.0 and fix new issues
Update mypy to 1.19.0, because the previous version was too old to work
with Python 3.14. However, this new version found new issues. Fix those.

Specifically:
osbuild/testutil/imports.py:29: error: Module has no attribute "util"  [attr-defined]
osbuild/testutil/imports.py:33: error: Module has no attribute "util"  [attr-defined]
osbuild/qemu.py:176: error: Module has no attribute "util"  [attr-defined]
^^^
Fix these by fixing the import to specify the actually used module.

osbuild/mounts.py:141: error: Incompatible types in assignment (expression has type "str", target has type "dict[str, Mount]")  [assignment]
^^^
Fix the type annotation, which was actually wrong.

Signed-off-by: Tomáš Hozza <thozza@redhat.com>