osbuild.spec: Add python3-dnf dependency for osbuild-tools
The recent change in https://github.com/osbuild/osbuild/pull/1896
removed the dnf dependency, leading to failures in osbuild-mpp with the
following error:

    ModuleNotFoundError: No module named 'dnf'

To fix it, add the python3-dnf dependency for the
osbuild-tools package.

Signed-off-by: Renata Ravanelli <rravanel@redhat.com>